version: 2

models:
  - name: int_orders_margin
    description: to model margin (revenue - purchase_cost) on a per order basis
    columns:
      - name: orders_id
        description: primary key
        tests:
          - unique
          - not_null
      - name: date_date
        description: date order placed
        tests:
          - not_null
      - name: revenue
        description: revenue per individual order
        tests:
          - not_null
      - name: quantity
        description: total number of products in order
        tests:
          - not_null
      - name: purchase_cost
        description: total cost to purchase products in an order (quantity * purchase_price)
        tests:
          - not_null
      - name: margin
        description: difference between revenue earned and purchase cost of an order (revenue - purchase_cost)
        tests:
          - not_null
  - name: int_orders_operational
    description: to model operating margin (margin + shipping_fee - log_cost - ship_cost) on a per order basis
    columns:
      - name: orders_id
        description: primary key
        tests:
          - unique
          - not_null
      - name: date_date
        description: date order placed
        tests:
          - not_null
      - name: operational_margin
        description: sales margin with shipping fee added and logisitics and shipping costs removed (margin + shipping_fee - log_cost - ship_cost)
        tests:
          - not_null
      - name: margin
        description: difference between revenue earned and purchase cost of an order (revenue - purchase_cost)
        tests:
          - not_null
      - name: quantity
        description: total number of products in order
        tests:
          - not_null
      - name: revenue
        description: revenue per individual order
        tests:
          - not_null
      - name: purchase_cost
        description: total cost to purchase products in an order (quantity * purchase_price)
        tests:
          - not_null
      - name: shipping_fee
        description: fee collected from customer to offset shipping costs
        tests:
          - not_null
      - name: logcost
        description: logistics cost of order
        tests:
          - not_null
  - name: int_sales_margin
    description: to join raw sales and product data in order to calculate margin
    columns:
      - name: order_pdt_id
        description: primary key
        tests:
          - unique
          - not_null
      - name: date_date
        description: date order placed
        tests:
          - not_null
      - name: orders_id
        description: order identifier
        tests:
          - not_null
      - name: products_id
        description: product identifier
        tests:
          - not_null
      - name: quantity
        description: total number of products in order
        tests:
          - not_null
      - name: revenue
        description: revenue per individual order
        tests:
          - not_null
      - name: purchase_price
        description: price of purchase of individual product in row
        tests:
          - not_null
      - name: purchase_cost
        description: total cost to purchase products in an order (quantity * purchase_price)
        tests:
          - not_null
      - name: margin
        description: difference between revenue earned and purchase cost of an order (revenue - purchase_cost)
        tests:
          - not_null
  - name: int_campaigns
    description: union of all raw campaign date from 4 sources
    columns:
      - name: date_date
        description: date of campaign
        tests:
          - not_null
      - name: campaign_key
        description: campaign id
        tests:
          - not_null
    tests:
      - unique: 
          column_name: "(date_date || '_' || campaign_key)"    
  - name: finance_days
    description: to model sales and product data at a daily grnaularity
    columns:
      - name: date_date
        tests:
          - unique
          - not_null
      - name: nb_transactions
        description: number of orders processed on date of row
        tests:
          - not_null
      - name: revenue
        description: revenue per individual order
        tests:
          - not_null
      - name: average_basket
        description: average revenue per order on a daily basis (revenue/nb_transactions)
        tests:
          - not_null
      - name: margin
        description: difference between revenue earned and purchase cost of orders (revenue - purchase_cost)
        tests:
          - not_null
      - name: operational_margin
        description: sales margin with shipping fee added and logisitics and shipping costs removed (margin + shipping_fee - log_cost - ship_cost)
        tests:
          - not_null
      - name: purchase_cost
        description: total cost to purchase products by day (quantity * purchase_price)
        tests:
          - not_null
      - name: shipping_fee
        description: total fees collected from customer to offset shipping costs by date of row
        tests:
          - not_null
      - name: logcost
        description: daily logistics cost of order
        tests:
          - not_null
      - name: quantity
        description: total number of products ordered on date of row
        tests:
          - not_null
sources:
  - name: raw
    schema: gz_raw_data
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: sales of Greenweez; one row per product_id found in orders_id
        # Freshness testing
        loaded_at_field: "CAST(date_date AS TIMESTAMP)"
        freshness:
          warn_after: {count: 90, period: day}
        columns:
          - name: date_date
            description: date of purchase
          - name: orders_id
            description: identifier of order
          - name: pdt_id
            description: identified of product
          - name: revenue
            description: revenue generated for product id in row
          - name: quantity
            description: number of products in order
        tests:
          - unique:
              column_name: "(orders_id || '_' || pdt_id)"
      - name: product
        identifier: raw_gz_product
        description: purchase price of each product; one row for each product_id
        columns:
          - name: products_id
            description: primary key
            tests:
              - unique
              - not_null
          - name: purchSE_PRICE
            description: purcahse price of product in row
      - name: ship
        identifier: raw_gz_ship
        description: shipping fee, logistics cost and ship cost of each orders_id
        columns:
          - name: orders_id
            description: primary key
            tests:
              - unique
              - not_null
          - name: shipping_fee
            description: fee charged to customer for shipping
          - name: shipping_fee_1
            description: duplicate values of shipping_fee column
          - name: logCost
            description: logistics cost of order
          - name: ship_cost
            description: shipping cost of order
      - name: adwords
        identifier: raw_gz_adwords
        description: adwords campaign data
        columns:
          - name: date_date
            description: campaign date
          - name: paid_source
            description: company where the ad campaign was run
          - name: campaign_key
            description: campaign identifier
        tests:
          - unique:
              column_name: "(date_date || '_' || campaign_key)"
      - name: bing
        identifier: raw_gz_bing
        description: bing campaign data
        columns:
          - name: date_date
            description: campaign date
          - name: paid_source
            description: company where the ad campaign was run
          - name: campaign_key
            description: campaign identifier
        tests:
          - unique:
              column_name: "(date_date || '_' || campaign_key)"
      - name: criteo
        identifier: raw_gz_criteo
        description: criteo campaign data
        columns:
          - name: date_date
            description: campaign date
          - name: paid_source
            description: company where the ad campaign was run
          - name: campaign_key
            description: campaign identifier
        tests:
          - unique:
              column_name: "(date_date || '_' || campaign_key)"
      - name: facebook
        identifier: raw_gz_facebook
        description: facebook campaign data
        columns:
          - name: date_date
            description: campaign date
          - name: paid_source
            description: company where the ad campaign was run
          - name: campaign_key
            description: campaign identifier
        tests:
          - unique:
              column_name: "(date_date || '_' || campaign_key)"
 